Update nord_connect
Signed-off-by: Orhant <orhantornaci@gmail.com>

diff --git a/scripts/nord_connect b/scripts/nord_connect
--- a/scripts/nord_connect
+++ b/scripts/nord_connect
@@ -3,63 +3,53 @@ shopt -s nocasematch
 
 [[ -n ${PRE_CONNECT} ]] && eval "${PRE_CONNECT}"
 
-RECONNECT_INTERVAL=${REFRESH_CONNECTION_INTERVAL:-120}
+CHANGE_PERIOD=${CHANGE_PERIOD:-300} # 5 dakika (300 saniye) olarak varsayılan değeri ayarladık
+REPEAT_PERIOD=${REPEAT_PERIOD:-7200} # 2 saat (7200 saniye) olarak varsayılan değeri ayarladık
 SERVER="$1"
-if [[ -z ${SERVER} || ${SERVER} == "null" ]]
-then
-  ## Get RECOMMENDED if internet accessible
-  if [[ $(curl -sm 5 "${CHECK_CONNECTION_URL:-https://www.google.com}") ]]
-  then
-    ## Obtain recommended server from API
+PREVIOUS_SERVERS=()
+LAST_RESET=$(date +%s)
+
+connect_to_server() {
+  local SERVER_TO_CONNECT=$1
+  current_sleep=1
+  until nordvpn connect "${SERVER_TO_CONNECT}" | grep -Ei -f /opt/reg-grep
+  do
+    if [ ${current_sleep} -gt 32 ]
+    then
+      echo -e "CRITICAL\tUnable to connect; exiting"
+      exit 1
+    fi
+    echo -e "WARNING\tUnable to connect; retrying in ${current_sleep} seconds."
+    sleep ${current_sleep}
+    current_sleep=$((current_sleep * 2))
+  done
+}
+
+while true; do
+  RECOMMENDED=$(nord_recommend)
+  SERVER=$(echo "${RECOMMENDED}" | jq --raw-output .servername)
+
+  # Önceki sunuculardan biriyle aynı sunucuya bağlanmamak için kontrol edin
+  while [[ " ${PREVIOUS_SERVERS[@]} " =~ " ${SERVER} " ]]; do
     RECOMMENDED=$(nord_recommend)
     SERVER=$(echo "${RECOMMENDED}" | jq --raw-output .servername)
+  done
 
-    ## Determine is valid servername
-    if [[ -z ${SERVER} || ${SERVER} == "null" ]]
-    then
-      if [[ -n ${CONNECTION_FILTERS} ]]
-      then
-        echo -e "WARNING\tInvalid connection string; retrying without filters"
-      else
-        echo -e "WARNING\tCannot connect to recommended; retrying with default"
-      fi
-      ## Let NordVPN client select the server
-      unset SERVER
-    else
-      echo "The recommended server is ${SERVER}"
-    fi
-  else
-    ## Firewall, notify that filters not to be used
-    if [[ -n ${CONNECTION_FILTERS} ]]
-    then
-      echo -e "INFO\tThe NordVPN FIREWALL is preventing evaluation of connection filters."
-      echo -e "INFO\tThis is expected on startup before the tunnel has been established."
-      if [ "${RECONNECT_INTERVAL}" -ne 0 ]
-      then
-        echo -e "INFO\tFilters will be evaluated on connection refresh."
-      fi
-      echo -e "INFO\tSet FIREWALL to 'false' to allow filter evaluation at startup."
-      echo -e "INFO\tRetrying now with default connect string."
-    fi
-    unset SERVER
-  fi
-else
-  ## Report the recommended server, unless called from nord_watch
-  pgrep -f "nord_watch" > /dev/null || echo "The recommended server is ${SERVER}"
-fi
+  # Sunucuya bağlan
+  connect_to_server "${SERVER}"
 
-## Make the connection
-current_sleep=1
-until nordvpn connect "${SERVER}" | grep -Ei -f /opt/reg-grep
-do
-  if [ ${current_sleep} -gt 32 ]
-  then
-    echo -e "CRITICAL\tUnable to connect; exiting"
-    exit 1
+  # Bağlandıktan sonra CHANGE_PERIOD süresi kadar bekle
+  sleep $CHANGE_PERIOD
+
+  # Mevcut sunucuyu önceki sunucular listesine ekleyin
+  PREVIOUS_SERVERS+=("${SERVER}")
+
+  # Eğer REPEAT_PERIOD süresi dolduysa, önceki sunucular listesini sıfırla
+  CURRENT_TIME=$(date +%s)
+  if (( CURRENT_TIME - LAST_RESET >= REPEAT_PERIOD )); then
+    PREVIOUS_SERVERS=()
+    LAST_RESET=$CURRENT_TIME
   fi
-  echo -e "WARNING\tUnable to connect; retrying in ${current_sleep} seconds."
-  sleep ${current_sleep}
-  current_sleep=$((current_sleep * 2))
 done
 
 [[ -n ${POST_CONNECT} ]] && eval "${POST_CONNECT}"
